import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
import io
import base64


def create_medical_report_pdf(
    patient_name="Unknown",
    dob="Unknown",
    gender="Unknown",
    test_type="Disease Detection",
    uploaded_image_path=None,
    model_result=None,
    llm_response=None,
    query_text=None
):
    """
    Generate a professional medical report PDF matching MacvaarAI format.

    Args:
        patient_name: Patient name
        dob: Date of birth
        gender: Patient gender
        test_type: Type of test/disease
        uploaded_image_path: Path to uploaded image (optional)
        model_result: Dict with label, confidence, summary
        llm_response: Dict with thought_process, key_findings, etc.
        query_text: User query/ask

    Returns:
        PDF bytes or file path
    """

    # Create PDF buffer
    pdf_buffer = io.BytesIO()

    # Create document
    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch,
        title="MacvaarAI Health Report"
    )

    # Container for PDF elements
    elements = []

    # Get styles
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#000000'),
        spaceAfter=6,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )

    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#1a1a1a'),
        spaceAfter=12,
        spaceBefore=12,
        fontName='Helvetica-Bold'
    )

    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=11,
        alignment=TA_JUSTIFY,
        spaceAfter=8,
        leading=14
    )

    # ═══════════════════════════════════════════════════════════════
    # HEADER SECTION
    # ═══════════════════════════════════════════════════════════════

    # Add logo placeholder
    header_table = Table(
        [
            [
                Paragraph("<b>MacvaarAI</b><br/><b>Health Assistant</b>",
                         ParagraphStyle('HeaderText', parent=styles['Normal'],
                                      fontSize=10, alignment=TA_CENTER))
            ]
        ],
        colWidths=[7.5*inch]
    )
    header_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
    ]))
    elements.append(header_table)

    # Title
    elements.append(Paragraph("MACVAAR HEALTH REPORT", title_style))
    elements.append(Paragraph("Generated by Macvaar AI Health System",
                             ParagraphStyle('Subtitle', parent=styles['Normal'],
                                          fontSize=11, alignment=TA_CENTER,
                                          textColor=colors.HexColor('#333333'))))
    elements.append(Spacer(1, 0.2*inch))

    # ═══════════════════════════════════════════════════════════════
    # PATIENT INFORMATION SECTION
    # ═══════════════════════════════════════════════════════════════

    report_date = datetime.now().strftime("%m/%d/%Y, %I:%M:%S %p")

    patient_info_data = [
        ["Patient:", patient_name],
        ["DOB:", dob],
        ["Gender:", gender],
        ["Report Generated:", report_date],
    ]

    patient_table = Table(patient_info_data, colWidths=[1.5*inch, 5.5*inch])
    patient_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#cccccc')),
    ]))
    elements.append(patient_table)
    elements.append(Spacer(1, 0.3*inch))

    # ═══════════════════════════════════════════════════════════════
    # ASK SECTION (Uploaded Image)
    # ═══════════════════════════════════════════════════════════════

    elements.append(Paragraph("Ask:", heading_style))

    if uploaded_image_path and os.path.exists(uploaded_image_path):
        try:
            elements.append(Image(uploaded_image_path, width=6*inch, height=3.5*inch))
            elements.append(Spacer(1, 0.1*inch))
        except:
            elements.append(Paragraph(
                "<i>[Image could not be displayed]</i>",
                normal_style
            ))
    elif query_text:
        elements.append(Paragraph(f"<b>Query:</b> {query_text}", normal_style))

    elements.append(Spacer(1, 0.2*inch))

    # ═══════════════════════════════════════════════════════════════
    # MACVAAR AI RESPONSE SECTION
    # ═══════════════════════════════════════════════════════════════

    elements.append(Paragraph("Macvaar AI Response:", heading_style))

    # Model Result
    if model_result:
        elements.append(Paragraph("<b>Model Result</b>",
                                 ParagraphStyle('SubHeading', parent=styles['Normal'],
                                              fontSize=12, fontName='Helvetica-Bold')))
        label = model_result.get('label', 'Unknown')
        elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{label}", normal_style))
        elements.append(Spacer(1, 0.1*inch))

        # Summary
        elements.append(Paragraph("<b>Summary</b>",
                                 ParagraphStyle('SubHeading', parent=styles['Normal'],
                                              fontSize=12, fontName='Helvetica-Bold')))
        summary = model_result.get('summary', 'No summary available')
        elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{summary}", normal_style))
        elements.append(Spacer(1, 0.1*inch))

    # LLM Response Sections - Always include with content or defaults
    llm_response = llm_response or {}

    # Thought Process
    thought = llm_response.get('thought_process', 'Analysis in progress. Please consult with healthcare provider for detailed clinical interpretation.')
    elements.append(Paragraph("<b>Thought Process</b>",
                             ParagraphStyle('SubHeading', parent=styles['Normal'],
                                          fontSize=12, fontName='Helvetica-Bold')))
    elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{thought}", normal_style))
    elements.append(Spacer(1, 0.1*inch))

    # Key Findings
    findings = llm_response.get('key_findings', '1. Model analysis completed. 2. Results require clinical correlation. 3. Consult healthcare professional for definitive diagnosis.')
    elements.append(Paragraph("<b>Key Findings</b>",
                             ParagraphStyle('SubHeading', parent=styles['Normal'],
                                          fontSize=12, fontName='Helvetica-Bold')))
    if isinstance(findings, list):
        for i, finding in enumerate(findings, 1):
            elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{i}. {finding}", normal_style))
    else:
        elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{findings}", normal_style))
    elements.append(Spacer(1, 0.1*inch))

    # Model Reasoning
    reasoning = llm_response.get('model_reasoning', 'AI model analyzed the provided medical data using trained neural networks. Results should be validated by qualified healthcare professionals.')
    elements.append(Paragraph("<b>Model Reasoning</b>",
                             ParagraphStyle('SubHeading', parent=styles['Normal'],
                                          fontSize=12, fontName='Helvetica-Bold')))
    elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{reasoning}", normal_style))
    elements.append(Spacer(1, 0.1*inch))

    # Recommended Steps
    steps = llm_response.get('recommended_steps', '1. Schedule appointment with relevant specialist. 2. Bring all medical records and test results. 3. Discuss AI analysis findings with healthcare provider. 4. Follow professional medical advice.')
    elements.append(Paragraph("<b>Recommended Steps</b>",
                             ParagraphStyle('SubHeading', parent=styles['Normal'],
                                          fontSize=12, fontName='Helvetica-Bold')))
    if isinstance(steps, list):
        for i, step in enumerate(steps, 1):
            elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{i}. {step}", normal_style))
    else:
        elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{steps}", normal_style))
    elements.append(Spacer(1, 0.1*inch))

    # Medical Risks
    risks = llm_response.get('medical_risks', 'Relying solely on AI analysis without professional medical consultation may lead to misdiagnosis or delayed treatment. Always seek qualified healthcare advice.')
    elements.append(Paragraph("<b>Medical Risks</b>",
                             ParagraphStyle('SubHeading', parent=styles['Normal'],
                                          fontSize=12, fontName='Helvetica-Bold')))
    if isinstance(risks, list):
        for risk in risks:
            elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;• {risk}", normal_style))
    else:
        elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{risks}", normal_style))
    elements.append(Spacer(1, 0.1*inch))

    # ═══════════════════════════════════════════════════════════════
    # FOOTER
    # ═══════════════════════════════════════════════════════════════

    elements.append(Spacer(1, 0.3*inch))
    elements.append(Paragraph(
        "For queries, contact admin@macvaarai.com",
        ParagraphStyle('Footer', parent=styles['Normal'],
                     fontSize=9, alignment=TA_CENTER,
                     textColor=colors.HexColor('#666666'))
    ))

    # Build PDF
    doc.build(elements)

    # Get PDF bytes
    pdf_buffer.seek(0)
    pdf_bytes = pdf_buffer.getvalue()

    # Save to file
    report_filename = f"Health_Report_{int(datetime.now().timestamp() * 1000)}.pdf"
    report_path = f"reports/{report_filename}"

    # Create reports directory if it doesn't exist
    os.makedirs("reports", exist_ok=True)

    with open(report_path, 'wb') as f:
        f.write(pdf_bytes)

    return {
        "status": "success",
        "filename": report_filename,
        "filepath": report_path,
        "pdf_bytes": pdf_bytes
    }


def generate_pdf_response(response_data, patient_info=None):
    """
    Wrapper function to generate PDF from API response.

    Args:
        response_data: Dict with model_result, llm_response, etc.
        patient_info: Dict with patient_name, dob, gender

    Returns:
        PDF file info or error
    """

    patient_info = patient_info or {}

    return create_medical_report_pdf(
        patient_name=patient_info.get('name', 'Unknown'),
        dob=patient_info.get('dob', 'Unknown'),
        gender=patient_info.get('gender', 'Unknown'),
        test_type=response_data.get('test_type', 'Disease Detection'),
        uploaded_image_path=response_data.get('image_path'),
        model_result=response_data.get('model_result'),
        llm_response=response_data.get('llm_response'),
        query_text=response_data.get('query')
    )
