import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image,
    PageBreak, KeepTogether
)
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
import io


def create_professional_medical_report(
    patient_name="Patient",
    dob="Unknown",
    gender="Unknown",
    test_type="Medical Analysis",
    uploaded_image_path=None,
    model_result=None,
    llm_response=None,
    query_text=None
):
    """
    Generate professional medical report PDF matching MacvaarAI template.
    """

    pdf_buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch,
        title="MacvaarAI Health Report"
    )

    elements = []
    styles = getSampleStyleSheet()

    # Custom Styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#000000'),
        spaceAfter=6,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )

    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=11,
        alignment=TA_CENTER,
        textColor=colors.HexColor('#333333'),
        spaceAfter=12
    )

    heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontSize=12,
        textColor=colors.HexColor('#000000'),
        spaceAfter=8,
        spaceBefore=8,
        fontName='Helvetica-Bold'
    )

    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=10,
        alignment=TA_JUSTIFY,
        spaceAfter=6,
        leading=12
    )

    # PAGE 1: HEADER + PATIENT INFO

    # Logo/Header
    header_text = Paragraph(
        "<b>MacvaarAI</b><br/><b>Health Assistant</b>",
        ParagraphStyle('Header', parent=styles['Normal'], fontSize=10, alignment=TA_CENTER)
    )
    elements.append(header_text)
    elements.append(Spacer(1, 0.15*inch))

    # Title
    elements.append(Paragraph("MACVAAR HEALTH REPORT", title_style))
    elements.append(Paragraph("Generated by Macvaar AI Health System", subtitle_style))
    elements.append(Spacer(1, 0.2*inch))

    # Patient Information Table
    report_date = datetime.now().strftime("%m/%d/%Y, %I:%M:%S %p")
    patient_data = [
        ["Patient:", patient_name],
        ["DOB:", dob],
        ["Gender:", gender],
        ["Report Generated:", report_date],
    ]

    patient_table = Table(patient_data, colWidths=[1.5*inch, 5*inch])
    patient_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#cccccc')),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.white, colors.HexColor('#f9f9f9')]),
    ]))
    elements.append(patient_table)
    elements.append(Spacer(1, 0.3*inch))

    # PAGE BREAK
    elements.append(PageBreak())

    # PAGE 2: IMAGE + RESPONSE HEADER

    elements.append(Paragraph("Ask:", heading_style))
    elements.append(Spacer(1, 0.1*inch))

    # Image
    if uploaded_image_path and os.path.exists(uploaded_image_path):
        try:
            img = Image(uploaded_image_path, width=6*inch, height=3.5*inch)
            elements.append(img)
            elements.append(Spacer(1, 0.2*inch))
        except:
            elements.append(Paragraph("<i>[Image could not be displayed]</i>", normal_style))

    elements.append(Spacer(1, 0.2*inch))

    # Response Section Header
    elements.append(Paragraph("Macvaar AI Response:", heading_style))
    elements.append(Spacer(1, 0.1*inch))

    # Model Result
    if model_result:
        elements.append(Paragraph("<b>Model Result</b>", heading_style))
        if model_result.get('label'):
            elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{model_result['label']}", normal_style))
        elements.append(Spacer(1, 0.08*inch))

        elements.append(Paragraph("<b>Summary</b>", heading_style))
        if model_result.get('summary'):
            elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{model_result['summary']}", normal_style))
        elements.append(Spacer(1, 0.08*inch))

    # PAGE BREAK
    elements.append(PageBreak())

    # PAGE 3+: DETAILED ANALYSIS

    # Ensure llm_response is dict
    llm_response = llm_response or {}

    # Thought Process
    thought = llm_response.get('thought_process',
        'The analysis has been completed by the AI model. Please consult with a qualified healthcare professional for clinical interpretation and recommendations.')
    elements.append(Paragraph("<b>Thought Process</b>", heading_style))
    elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{thought}", normal_style))
    elements.append(Spacer(1, 0.1*inch))

    # Key Findings
    findings = llm_response.get('key_findings',
        '1. Model analysis completed successfully. 2. Results require clinical correlation with patient symptoms. 3. Consult healthcare professional for definitive diagnosis.')
    elements.append(Paragraph("<b>Key Findings</b>", heading_style))
    if isinstance(findings, list):
        for i, finding in enumerate(findings, 1):
            elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{i}. {finding}", normal_style))
    else:
        elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{findings}", normal_style))
    elements.append(Spacer(1, 0.1*inch))

    # Model Reasoning
    reasoning = llm_response.get('model_reasoning',
        'The AI model analyzed the provided medical data using trained deep learning algorithms. Results are based on pattern recognition from training data and should be validated by qualified medical professionals.')
    elements.append(Paragraph("<b>Model Reasoning</b>", heading_style))
    elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{reasoning}", normal_style))
    elements.append(Spacer(1, 0.1*inch))

    # Recommended Steps
    steps = llm_response.get('recommended_steps',
        '1. Schedule consultation with relevant medical specialist. 2. Bring all medical records and test results. 3. Discuss AI analysis with healthcare provider. 4. Follow professional medical advice for treatment.')
    elements.append(Paragraph("<b>Recommended Steps</b>", heading_style))
    if isinstance(steps, list):
        for i, step in enumerate(steps, 1):
            elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{i}. {step}", normal_style))
    else:
        elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{steps}", normal_style))
    elements.append(Spacer(1, 0.1*inch))

    # Medical Risks
    risks = llm_response.get('medical_risks',
        'Relying solely on AI analysis without professional medical consultation may result in misdiagnosis or delayed treatment. Over-reliance on numerical results without clinical context could lead to unnecessary or inappropriate interventions.')
    elements.append(Paragraph("<b>Medical Risks</b>", heading_style))
    if isinstance(risks, list):
        for risk in risks:
            elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;• {risk}", normal_style))
    else:
        elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{risks}", normal_style))
    elements.append(Spacer(1, 0.15*inch))

    # FOOTER
    elements.append(Spacer(1, 0.2*inch))
    footer_text = Paragraph(
        "For queries, contact admin@macvaarai.com",
        ParagraphStyle('Footer', parent=styles['Normal'], fontSize=9, alignment=TA_CENTER,
                      textColor=colors.HexColor('#666666'))
    )
    elements.append(footer_text)

    # Build PDF
    doc.build(elements)

    # Get PDF bytes
    pdf_buffer.seek(0)
    pdf_bytes = pdf_buffer.getvalue()

    # Save to file
    report_filename = f"Health_Report_{int(datetime.now().timestamp() * 1000)}.pdf"
    report_path = f"reports/{report_filename}"

    os.makedirs("reports", exist_ok=True)

    with open(report_path, 'wb') as f:
        f.write(pdf_bytes)

    return {
        "status": "success",
        "filename": report_filename,
        "filepath": report_path,
        "pdf_bytes": pdf_bytes
    }
