import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image,
    PageBreak, Frame, PageTemplate
)
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.pdfgen import canvas
import io


class NumberedCanvas(canvas.Canvas):
    """Add page numbers to PDF"""
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._saved_state = None

    def showPage(self):
        self._saved_state = dict(self.__dict__)
        self._startPage()

    def save(self):
        page_num = self.getPageNumber()
        if page_num > 1:
            self.setFont("Helvetica", 9)
            self.drawRightString(7.5*inch, 0.4*inch, f"Page {page_num}")
        canvas.Canvas.save(self)


def create_exact_medical_report(
    patient_name="Patient",
    dob="Unknown",
    gender="Unknown",
    test_type="Medical Analysis",
    uploaded_image_path=None,
    model_result=None,
    llm_response=None,
    query_text=None
):
    """
    Create EXACT replica PDF matching user's uploaded format.
    """

    pdf_buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=letter,
        rightMargin=0.65*inch,
        leftMargin=0.65*inch,
        topMargin=0.65*inch,
        bottomMargin=0.65*inch,
        title="MACVAAR HEALTH REPORT",
        canvasmaker=NumberedCanvas
    )

    elements = []
    styles = getSampleStyleSheet()

    # Exact Styles from Reference PDF
    logo_style = ParagraphStyle(
        'Logo',
        parent=styles['Normal'],
        fontSize=9,
        alignment=TA_CENTER,
        textColor=colors.HexColor('#000000'),
        fontName='Helvetica-Bold',
        spaceAfter=0
    )

    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=colors.HexColor('#000000'),
        spaceAfter=2,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold',
        leading=20
    )

    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=10,
        alignment=TA_CENTER,
        textColor=colors.HexColor('#333333'),
        spaceAfter=12,
        fontName='Helvetica'
    )

    heading_style = ParagraphStyle(
        'Heading',
        parent=styles['Heading2'],
        fontSize=11,
        textColor=colors.HexColor('#000000'),
        spaceAfter=4,
        spaceBefore=6,
        fontName='Helvetica-Bold',
        leading=12
    )

    normal_style = ParagraphStyle(
        'Normal',
        parent=styles['Normal'],
        fontSize=10,
        alignment=TA_JUSTIFY,
        spaceAfter=6,
        leading=13,
        fontName='Helvetica'
    )

    body_indent_style = ParagraphStyle(
        'BodyIndent',
        parent=styles['Normal'],
        fontSize=10,
        alignment=TA_JUSTIFY,
        spaceAfter=6,
        leading=13,
        fontName='Helvetica',
        leftIndent=0.25*inch
    )

    # ================================================================
    # PAGE 1: HEADER + PATIENT INFO
    # ================================================================

    # Logo/Header - Exact format
    elements.append(Paragraph("MacvaarAI<br/>Health Assistant", logo_style))
    elements.append(Spacer(1, 0.12*inch))

    # Title
    elements.append(Paragraph("MACVAAR HEALTH REPORT", title_style))
    elements.append(Paragraph("Generated by Macvaar AI Health System", subtitle_style))
    elements.append(Spacer(1, 0.25*inch))

    # Patient Information Table - Exact format from PDF
    report_date = datetime.now().strftime("%m/%d/%Y, %I:%M:%S %p")
    patient_data = [
        ["Patient:", patient_name],
        ["DOB:", dob],
        ["Gender:", gender],
        ["Report Generated:", report_date],
    ]

    patient_table = Table(patient_data, colWidths=[1.3*inch, 5.2*inch])
    patient_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#999999')),
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#ffffff')),
    ]))
    elements.append(patient_table)
    elements.append(Spacer(1, 0.3*inch))

    # ================================================================
    # PAGE 2: IMAGE + RESPONSE START
    # ================================================================
    elements.append(PageBreak())

    elements.append(Paragraph("Ask:", heading_style))
    elements.append(Spacer(1, 0.1*inch))

    # Image - Exact size
    if uploaded_image_path and os.path.exists(uploaded_image_path):
        try:
            img = Image(uploaded_image_path, width=5.7*inch, height=3.2*inch)
            elements.append(img)
        except:
            pass

    elements.append(Spacer(1, 0.2*inch))

    # Response Header
    elements.append(Paragraph("Macvaar AI Response:", heading_style))
    elements.append(Spacer(1, 0.08*inch))

    # Model Result - Exact format
    if model_result:
        elements.append(Paragraph("<b>Model Result</b>", heading_style))
        if model_result.get('label'):
            elements.append(Paragraph(model_result['label'], body_indent_style))
        elements.append(Spacer(1, 0.08*inch))

        elements.append(Paragraph("<b>Summary</b>", heading_style))
        if model_result.get('summary'):
            elements.append(Paragraph(model_result['summary'], body_indent_style))
        elements.append(Spacer(1, 0.08*inch))

    # ================================================================
    # PAGE 3+: DETAILED ANALYSIS
    # ================================================================
    elements.append(PageBreak())

    llm_response = llm_response or {}

    # Thought Process
    thought = llm_response.get('thought_process',
        'The analysis has been completed by the AI model. Please consult with a qualified healthcare professional for clinical interpretation and medical advice.')
    elements.append(Paragraph("<b>Thought Process</b>", heading_style))
    elements.append(Paragraph(thought, body_indent_style))
    elements.append(Spacer(1, 0.08*inch))

    # Key Findings
    findings = llm_response.get('key_findings',
        '1. Model analysis completed successfully. 2. Results require clinical correlation with patient symptoms. 3. Consult healthcare professional for definitive diagnosis.')
    elements.append(Paragraph("<b>Key Findings</b>", heading_style))
    if isinstance(findings, list):
        findings_text = ""
        for i, finding in enumerate(findings, 1):
            findings_text += f"{i}. {finding} "
        elements.append(Paragraph(findings_text, body_indent_style))
    else:
        elements.append(Paragraph(findings, body_indent_style))
    elements.append(Spacer(1, 0.08*inch))

    # Model Reasoning
    reasoning = llm_response.get('model_reasoning',
        'The AI model analyzed the provided medical data using trained deep learning algorithms. Results are based on pattern recognition and should be validated by qualified medical professionals.')
    elements.append(Paragraph("<b>Model Reasoning</b>", heading_style))
    elements.append(Paragraph(reasoning, body_indent_style))
    elements.append(Spacer(1, 0.08*inch))

    # Recommended Steps
    steps = llm_response.get('recommended_steps',
        '1. Schedule consultation with relevant medical specialist. 2. Bring all medical records and test results. 3. Discuss AI analysis with healthcare provider. 4. Follow professional medical advice for treatment.')
    elements.append(Paragraph("<b>Recommended Steps</b>", heading_style))
    if isinstance(steps, list):
        steps_text = ""
        for i, step in enumerate(steps, 1):
            steps_text += f"{i}. {step} "
        elements.append(Paragraph(steps_text, body_indent_style))
    else:
        elements.append(Paragraph(steps, body_indent_style))
    elements.append(Spacer(1, 0.08*inch))

    # Medical Risks
    risks = llm_response.get('medical_risks',
        'Relying solely on AI analysis without professional medical consultation may result in misdiagnosis or delayed treatment. Over-reliance on numerical results without clinical context could lead to inappropriate medical interventions.')
    elements.append(Paragraph("<b>Medical Risks</b>", heading_style))
    if isinstance(risks, list):
        risks_text = ""
        for risk in risks:
            risks_text += f"• {risk} "
        elements.append(Paragraph(risks_text, body_indent_style))
    else:
        elements.append(Paragraph(risks, body_indent_style))

    elements.append(Spacer(1, 0.2*inch))

    # Footer
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        alignment=TA_CENTER,
        textColor=colors.HexColor('#666666'),
        fontName='Helvetica'
    )
    elements.append(Paragraph("For queries, contact admin@macvaarai.com", footer_style))

    # Build PDF
    doc.build(elements)

    # Get PDF bytes
    pdf_buffer.seek(0)
    pdf_bytes = pdf_buffer.getvalue()

    # Save to file
    report_filename = f"Health_Report_{int(datetime.now().timestamp() * 1000)}.pdf"
    report_path = f"reports/{report_filename}"

    os.makedirs("reports", exist_ok=True)

    with open(report_path, 'wb') as f:
        f.write(pdf_bytes)

    return {
        "status": "success",
        "filename": report_filename,
        "filepath": report_path,
        "pdf_bytes": pdf_bytes
    }
