// src/utils/reportDownloader.js
import { jsPDF } from "jspdf";

export const downloadReportPDF = async (report) => {
  if (!report) return;
  const doc = new jsPDF();

  /* ---------- Helper: Page Border ---------- */
  const drawPageBorder = () => {
    doc.setDrawColor(180, 180, 180); // soft gray border
    doc.setLineWidth(0.5);
    doc.rect(8, 8, 194, 281); // A4 border
  };

  /* ---------- Helper: Add Logo ---------- */
  const loadLogo = async () => {
    return await fetch("/1.png")
      .then((res) => res.blob())
      .then(
        (blob) =>
          new Promise((resolve) => {
            const reader = new FileReader();
            reader.onload = () => resolve(reader.result);
            reader.readAsDataURL(blob);
          })
      );
  };

  /* ---------------- COVER PAGE ---------------- */
  drawPageBorder();

  try {
    const logo = await loadLogo();
    doc.addImage(logo, "PNG", 85, 25, 40, 40); // centered
  } catch {}

  doc.setFontSize(24).setFont("helvetica", "bold");
  doc.text("MACVAAR HEALTH REPORT", 105, 85, { align: "center" });

  doc.setFontSize(14).setFont("helvetica", "normal");
  doc.text("Generated by Macvaar AI Health System", 105, 95, { align: "center" });

  // Patient info
  let y = 120;
  const addLineCover = (label, value) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, 30, y);
    doc.setFont("helvetica", "normal");
    doc.text(String(value || "null"), 90, y);
    y += 12;
  };

  addLineCover("Appointment ID", report.appointmentId);
  addLineCover("Patient", report.patientName);
  addLineCover("Doctor", report.doctorName);
  addLineCover("Exam Type", report.examType);
  addLineCover("Start", report.startDateUtc);
  addLineCover("End", report.endDateUtc);
  addLineCover("Duration", (report.durationInMinutes || "null") + " min");

  // Footer (no page number on page 1)
  doc.setFontSize(10).setFont("helvetica", "italic");
  doc.text("Confidential Medical Report", 105, 280, { align: "center" });

  /* ---------------- READINGS PAGE ---------------- */
  doc.addPage();
  drawPageBorder();

  try {
    const logo = await loadLogo();
    doc.addImage(logo, "PNG", 170, 12, 25, 18); // top-right
  } catch {}

  doc.setFontSize(16).setFont("helvetica", "bold");
  doc.text("Readings", 105, 25, { align: "center" });

  let yDetail = 45;
  let rowIndex = 0;
  let pageNumber = 2;

  for (let r of report.readings || []) {
    if (yDetail > 260) {
      // footer before new page
      doc.setFontSize(10).setFont("helvetica", "normal");
      doc.text("For any queries, reach out to admin@macvaarai.com", 15, 292);
      doc.text(`Page ${pageNumber}`, 195, 292, { align: "right" });

      // new page
      doc.addPage();
      drawPageBorder();
      try {
        const logo = await loadLogo();
        doc.addImage(logo, "PNG", 170, 12, 25, 18); // top-right again
      } catch {}
      doc.setFontSize(16).setFont("helvetica", "bold");
      doc.text("Readings", 105, 25, { align: "center" });

      yDetail = 45;
      pageNumber++;
    }

    // alternating row background
    if (rowIndex % 2 === 0) {
      doc.setFillColor(245, 245, 245);
      doc.rect(14, yDetail - 6, 180, 12, "F");
    }

    doc.setFont("helvetica", "bold");
    doc.text(r.Sensor || "null", 20, yDetail);
    doc.setFont("helvetica", "normal");

    if ((r.SensorMode === "image" || r.SensorMode === "audio") && r.SensorSettings) {
      doc.setTextColor(0, 0, 255);
      doc.textWithLink(
        r.SensorMode === "audio" ? "Play Audio" : "View File",
        120,
        yDetail,
        { url: r.SensorSettings }
      );
      doc.setTextColor(0, 0, 0);
    } else {
      let value = r.SensorData || "null";
      if (r.SensorSettings && r.SensorMode === "Default") {
        value += ` (${r.SensorSettings})`;
      }
      doc.text(String(value), 120, yDetail);
    }

    yDetail += 12;
    rowIndex++;
  }

  // Final page footer
  doc.setFontSize(10).setFont("helvetica", "normal");
  doc.text("For any queries, reach out to admin@macvaarai.com", 15, 292);
  doc.text(`Page ${pageNumber}`, 195, 292, { align: "right" });

  doc.save(`Appointment_${report.appointmentId}.pdf`);
};
