import json
import re
from transformers import pipeline

# Use free HuggingFace model for medical text generation
try:
    # Using google/flan-t5-large - free, open-source, medical-aware
    llm_pipeline = pipeline(
        "text2text-generation",
        model="google/flan-t5-large",
        device=-1  # Use CPU (-1) or GPU (0) if available
    )
    print("✅ HuggingFace Model Loaded: google/flan-t5-large")
except Exception as e:
    print(f"⚠️ Error loading HuggingFace model: {e}")
    llm_pipeline = None

SYSTEM_PROMPT_MEDICAL_DOCTOR = """
You are a medical AI assistant. Your job is to provide only factual, evidence-based medical insights.

Strictly follow:
1. Respond only with structured, clinical, and medically accurate content.
2. Do not include any self-references like "As an AI" or "I think".
3. Do not speculate. If unsure, state clearly and move on.
4. Only provide analysis, explanation, and recommendations in clear sections like this JSON format:
   {
  "thought_process": "...",
  "medical_explanation": "...",
  "key_findings": "...",
  "model_reasoning": "...",
  "recommended_steps": "...",
  "medical_risks": "...",
  "references": [
  "Provide official and trusted medical sources with actual links. Always include two or more links. Use sources like CDC, WHO, NIH, Mayo Clinic, PubMed articles"]
}


Avoid:
- Hallucinations
- Internal reasoning
- Generated-by-AI notes
- Hypotheticals unless medically standard
"""

# Extract only JSON portion from model response
def extract_json_block(text: str):
    match = re.search(r"\{[\s\S]+\}", text)
    if match:
        return match.group(0)
    return None

# Ask HuggingFace model for medical analysis
def ask_together(
    question: str,
    system_prompt: str = SYSTEM_PROMPT_MEDICAL_DOCTOR,
    model: str = "google/flan-t5-large",
    max_tokens: int = 2048,
    temperature: float = 0.3,
    timeout: int = 10
):
    try:
        if not llm_pipeline:
            print("⚠️ HuggingFace model not loaded. LLM enrichment disabled.")
            return None

        # Combine system prompt with question
        full_prompt = f"{system_prompt}\n\nQuestion: {question}"

        # Generate response using HuggingFace pipeline
        response = llm_pipeline(
            full_prompt,
            max_length=min(max_tokens, 512),  # Limit for faster response
            temperature=temperature,
            do_sample=True,
            top_p=0.95
        )

        content = response[0]["generated_text"].strip()

        try:
            # Try to extract JSON block
            json_str = extract_json_block(content)
            if json_str:
                parsed = json.loads(json_str)
                return parsed
            else:
                # If no JSON, return structured response with the generated text
                return {
                    "thought_process": content[:200] if len(content) > 200 else content,
                    "medical_explanation": content,
                    "key_findings": "See medical explanation above",
                    "model_reasoning": "Generated using HuggingFace Flan-T5 model",
                    "medical_risks": "Consult with healthcare provider for complete assessment",
                    "recommended_steps": "1. Follow up with medical professional 2. Schedule appropriate tests 3. Monitor symptoms",
                    "references": "Generated by open-source LLM"
                }

        except Exception as e:
            return {
                "thought_process": "",
                "medical_explanation": content,
                "key_findings": "Analysis generated",
                "model_reasoning": "HuggingFace Flan-T5 analysis",
                "medical_risks": "Please verify with healthcare provider",
                "recommended_steps": "Consult medical professional",
                "references": "Open-source LLM generated content"
            }

    except Exception as e:
        print(f"⚠️ HuggingFace LLM Error: {str(e)}")
        return None

# Final JSON structure builder
def build_response_json(
    text=None,
    file_type=None,
    model_result=None,
    llm_response=None
):
    return {
        "input_type": "text+file" if text and file_type else "text" if text else "file",
        "query": text,
        "file_type": file_type,
        "model_result": model_result,
        "llm_response": llm_response
    }